name: dockerhub_push_new
on:
  workflow_dispatch:
env:
  DOCKER_IMAGE: sreeharsha235/test_repository
jobs:
  Pull_Ubuntu_Docker_Image:
    name: Pull Ubuntu Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: docker.image('ubuntu:latest').pull()
  Run_Docker_Image:
    name: Run Docker Image
    runs-on: ubuntu-latest
    needs: Pull_Ubuntu_Docker_Image
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: docker.image('ubuntu:latest').run('--rm', 'echo "Hello, world!"')
  Push_Image_to_Docker_Hub:
    name: Push Image to Docker Hub
    runs-on: ubuntu-latest
    needs: Run_Docker_Image
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: |-
#             docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
#                                     sh 'docker push sreeharsha235/test_repository:latest'
#                                 }
