name: Docker
on:
  workflow_dispatch:
jobs:
  Pull_Docker_Image:
    name: Pull Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: sh "sudo docker pull alpine:latest"
  Run_Docker_Container:
    name: Run Docker Container
    runs-on: ubuntu-latest
    needs: Pull_Docker_Image
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: sh "sudo docker run --rm alpine:latest echo 'Hello from Docker container!'"
