name: docker
on:
  workflow_dispatch:
env:
  DOCKER_IMAGE: sreeharsha235/test_repository
  DOCKERHUB_USERNAME: sreeharsha235
  DOCKERHUB_PASSWORD: Password@123
jobs:
  Pull_Ubuntu_Docker_Image:
    name: Pull Ubuntu Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: sh "sudo docker pull ubuntu:latest"
  Run_Docker_Image:
    name: Run Docker Image
    runs-on: ubuntu-latest
    needs: Pull_Ubuntu_Docker_Image
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: sh "sudo docker run --rm ubuntu:latest echo 'Hello, world!'"
  Push_Image_to_Docker_Hub:
    name: Push Image to Docker Hub
    runs-on: ubuntu-latest
    needs: Run_Docker_Image
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: |-
#             sh "sudo docker login -u ${{ env.DOCKERHUB_USERNAME }} -p ${{ env.DOCKERHUB_PASSWORD }}"
#                                 sh "sudo docker tag ubuntu:latest ${{ env.DOCKER_IMAGE }}:latest"
#                                 sh "sudo docker push ${{ env.DOCKER_IMAGE }}:latest"
