name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Building"

      - name: Test
        run: echo "Testing"

      - name: Deploy
        run: echo "Deploying"

      - name: Build and Notify
        uses: ./.github/actions/Composite_Function.yml
        
