name: Simple Workflow

on:
  push:
    branches:
      - main
 
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: echo "Building"

      - name: Test
        shell: bash
        run: echo "Testing"

      - name: Deploy
        shell: bash
        run: echo "Deploying"

      - name: Notify Build Status
        run: |
          echo "Calling Composite_Function..."
          chmod +x ./.github/actions/ 
          #Composite_Function.yml
          echo "Composite_Function called successfully."
