name: Simple Workflow

on:
  push:
    branches:
      - main
 
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: bash
        run: echo "Building"

      - name: Test
        shell: bash
        run: echo "Testing"

      - name: Deploy
        shell: bash
        run: echo "Deploying"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify Build Status
        uses: action.yml@main
