name: Simple Workflow

on:
  push:
    branches:
      - main
 
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Add this line to checkout the repository

      - name: Build
        run: echo "Building"

      - name: Test
        run: echo "Testing"

      - name: Deploy
        run: echo "Deploying"

      - name: Notify Build Status
        uses: ./.github/actions/Composite_Function.yml
