name: Build and Notify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Trigger to allow manual execution from GitHub Actions UI

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Simulate error
        run: |
          exit 1
        
      - name: Send notification to Microsoft Teams
        if: always()
        run: |
          mention="<at>sreehass@amd.com</at>\n"
          mentionedId="sreehass@amd.com"
          mentionedName="A S S K, Sreeharsha"
          
          # Get the GitHub workflow run URL
          JOB_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          
          payload='{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "'"$mention"'",
                      "color": "good"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Job Name:** '"$JOB_NAME"'",
                      "color": "good"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Job URL:** [View Job]('"$JOB_URL"')",
                      "color": "good"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Status:** PASS",
                      "color": "good"
                    }
                  ],
                  "msteams": {
                    "entities": [
                      {
                        "type": "mention",
                        "text": "<at>sreehass@amd.com</at>",
                        "mentioned": {
                          "id": "'"$mentionedId"'",
                          "name": "'"$mentionedName"'"
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }'
          
          echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
    env:
      JOB_NAME: Build and Notify
 
