name: Build and Notify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Trigger to allow manual execution from GitHub Actions UI

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send notification to Microsoft Teams
        if: always()
        run: |
          mention="<at>sreehass@amd.com</at>\n"
          mentionedId="sreehass@amd.com"
          mentionedName="A S S K, Sreeharsha"
          successEmoji="✅"  # Green tick for success
          failureEmoji="❌"   # Red cross for failure
          successTag="sreehass"   # Tag sreehass for success
          failureTag="apinapak"   # Tag apinapak for failure
          
          # Get the GitHub workflow run URL
          JOB_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          
          # Determine the job status
          if [ -z "${{ steps.error }}" ]; then
            status="PASS"
            color="good"  # Green color for success
            emoji="$successEmoji"
            mentionId="$mentionedId"
            mentionName="$mentionedName"
          else
            status="FAIL"
            color="attention"  # Orange color for failure
            emoji="$failureEmoji"
            mentionId="apinapak@amd.com"
            mentionName="Pinapaka, Abhilash Sarath Teja"
          fi
          
          # Generate the payload for the notification
          payload='{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "<at>'"$mention"'</at>",
                      "color": "'"$color"'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Job Name:** '"$JOB_NAME"'",
                      "color": "'"$color"'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Job URL:** [View Job]('"$JOB_URL"')",
                      "color": "'"$color"'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Status:** '"$status $emoji"'",
                      "color": "'"$color"'"
                    }
                  ],
                  "msteams": {
                    "entities": [
                      {
                        "type": "mention",
                        "text": "<at>'"$mentionId"'</at>",
                        "mentioned": {
                          "id": "'"$mentionId"'",
                          "name": "'"$mentionName"'"
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }'
          
          # Send the payload to Microsoft Teams
          echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
    env:
      JOB_NAME: Build and Notify  
