name: Build and Notify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Trigger to allow manual execution from GitHub Actions UI

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    
    steps:
      #- name: Simulate error
      #  run: exit 1
      #  id: error
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get commit information
        id: commit
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          
          echo "::set-output name=commit_hash::$COMMIT_HASH"
          echo "::set-output name=branch_name::$BRANCH_NAME"
          
      - name: Determine mention based on status
        id: mention
        run: |
          if [ -z "${{ steps.error }}" ]; then
            status="PASS ✅"
            color="good"
            mention="<at>sreehass@amd.com</at>"
            mentionedId="sreehass@amd.com"
            mentionedName="A S S K, Sreeharsha"
          else
            status="FAIL ❌"
            color="attention"
            mention="<at>apinapak@amd.com</at>"
            mentionedId="apinapak@amd.com"
            mentionedName="Pinapaka, Abhilash Sarath Teja"
          fi
          echo "::set-output name=mention::$mention"
          echo "::set-output name=status::$status"
          echo "::set-output name=color::$color"
          echo "::set-output name=mentionedId::$mentionedId"
          echo "::set-output name=mentionedName::$mentionedName"
          
      - name: Send notification to Microsoft Teams
        if: always()
        run: |
          # Get the mention based on status
          MENTION=$(echo "${{ steps.mention.outputs.mention }}")
          STATUS=$(echo "${{ steps.mention.outputs.status }}")
          COLOR=$(echo "${{ steps.mention.outputs.color }}")
          MENTIONED_NAME=$(echo "${{ steps.mention.outputs.mentionedName }}")
          
          # Generate the payload for the notification
          payload='{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "'"$MENTIONED_NAME"'",
                      "color": "'"$COLOR"'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "Status: '"$STATUS"'",
                      "color": "'"$COLOR"'"
                    }
                  ]
                }
              }
            ]
          }'
          
          # Send the payload to Microsoft Teams
          echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
    env:
      JOB_NAME: Build and Notify
