name: Build and Notify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Build
        run: echo "Building" # Replace this with your build command
      
      - name: Send notification to Microsoft Teams
        env:
          JOB_NAME: ${{ github.workflow }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          jobStatus=$(curl -s -o /dev/null -w "%{http_code}" "")
          if [[ $jobStatus -eq 200 ]]; then
            COLOR="good"
            STATUS_LABEL="PASS"
          else
            COLOR="attention"
            STATUS_LABEL="FAIL"
          fi
          
          mention="<at>sreehass@amd.com</at>\n"
          mentionedId="sreehass@amd.com"
          mentionedName="A S S K, Sreeharsha"
          
          payload='{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "'"$mention"'",
                      "color": "'"$COLOR"'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Job Name:** '"$JOB_NAME"'",
                      "color": "'"$COLOR"'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Status:** '"$STATUS_LABEL"'",
                      "color": "'"$COLOR"'"
                    }
                  ],
                  "msteams": {
                    "entities": [
                      {
                        "type": "mention",
                        "text": "<at>sreehass@amd.com</at>",
                        "mentioned": {
                          "id": "'"$mentionedId"'",
                          "name": "'"$mentionedName"'"
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }'
          
          escapedPayload=$(echo "$payload" | sed 's/"/\\\\"/g')
          
          curl -X POST -H 'Content-Type: application/json' -d "$escapedPayload" 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
