name: Build and Notify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Trigger to allow manual execution from GitHub Actions UI

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run tests
        # Replace this with your actual test running command
        run: |
          # Example command
          echo "Running tests..."
          exit 1 # Replace this with the actual test command, exit 0 for success, exit 1 for failure
      
      - name: Determine job status and mention details
        id: status
        run: |
          if [ -z "${{ steps.error }}" ]; then
            status="✔ PASS"
            mention="<at>sreehass@amd.com</at>\n"
            mentionedId="sreehass@amd.com"
            mentionedName="A S S K, Sreeharsha"
          else
            status="❌ FAIL"
            mention="<at>apinapak@amd.com</at>\n"
            mentionedId="apinapak@amd.com"
            mentionedName="Pinapaka, Abhilash Sarath Teja"
          fi
          echo "::set-output name=status::$status"
          echo "::set-output name=mention::$mention"
          echo "::set-output name=mentionedId::$mentionedId"
          echo "::set-output name=mentionedName::$mentionedName"
      
      - name: Send notification to Microsoft Teams
        if: always()
        run: |
          # Get the GitHub workflow run URL
          JOB_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          
          # Generate the payload for the notification
          payload='{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "text": "'${{ steps.status.outputs.mention }}'",
                      "color": "'${{ steps.status.outputs.color }}'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Status:** ${{ steps.status.outputs.status }}",
                      "color": "'${{ steps.status.outputs.color }}'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Job Name:** ${{ github.workflow }}",
                      "color": "'${{ steps.status.outputs.color }}'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Job URL:** [View Job]('"$JOB_URL"')",
                      "color": "'${{ steps.status.outputs.color }}'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Repository URL:** https://github.com/sreeharsha-alluri/Jenkins_to_GHA.git",
                      "color": "'${{ steps.status.outputs.color }}'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Build Number:** ${{ github.run_number }}",
                      "color": "'${{ steps.status.outputs.color }}'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Branch Name:** ${{ github.ref }}",
                      "color": "'${{ steps.status.outputs.color }}'"
                    },
                    {
                      "type": "TextBlock",
                      "text": "**Latest Commit:** ${{ github.sha }}",
                      "color": "'${{ steps.status.outputs.color }}'"
                    }
                  ],
                  "msteams": {
                    "entities": [
                      {
                        "type": "mention",
                        "text": "'${{ steps.status.outputs.mention }}'",
                        "mentioned": {
                          "id": "'${{ steps.status.outputs.mentionedId }}'",
                          "name": "'${{ steps.status.outputs.mentionedName }}'"
                        }
                      }
                    ]
                  }
                }
              }
            ]
          }'
          
          # Send the payload to Microsoft Teams
          echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- '${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URL }}'
